#!/usr/bin/env/php 

<?php

/**
 * @copyright 2021 - N'Guessan Kouadio Elisée (eliseekn@gmail.com)
 * @license MIT (https://opensource.org/licenses/MIT)
 * @link https://github.com/eliseekn/tinymvc
 */

/**
 * Application command line interface
 */

require_once 'vendor/autoload.php';
require_once 'config/env.php';

//get command line arguments
$options = getopt('', [
    'help', 
    'make',
    'database',
    'seed::',
    'schema::',
    'query::',
    'fetch::',
    'db::',
    'resource::',
    'controller::',
    'namespace::',
    'model::', 
    'migration::', 
    'request::', 
    'middleware::', 
    'execute',
    'delete', 
    'reset',
]);

//handle command line arguments
if (
    array_key_exists('database', $options) &&
    !array_key_exists('help', $options) &&
    !array_key_exists('make', $options)
) {
    unset($options['database']);
    \Framework\Console\Database::handle($options);
}

else if (
    array_key_exists('make', $options) &&
    !array_key_exists('database', $options) &&
    !array_key_exists('help', $options)
) {
    unset($options['make']);
    \Framework\Console\Maker::handle($options);
}

else {
    $help_message = '[+] Command line arguments:' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '  --database (Manage database operations)' . PHP_EOL;
    $help_message .= '      --schema=posts                          Create posts database with utf8 encoding character' . PHP_EOL;
    $help_message .= '      --schema=posts,comments                 Create posts and comments databases' . PHP_EOL;
    $help_message .= '      --schema=posts --delete                 Delete posts database' . PHP_EOL;
    $help_message .= '      --schema=posts,comments --delete        Delete posts and comments databases' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '      --migration=all                         Migrate all tables' . PHP_EOL;
    $help_message .= '      --migration=posts                       Migrate posts table only' . PHP_EOL;
    $help_message .= '      --migration=posts,comments              Migrate posts and comments tables only' . PHP_EOL;
    $help_message .= '      --migration=all --seed=all              Migrate all tables and insert all seeds' . PHP_EOL;
    $help_message .= '      --migration=posts,comments --delete     Drop posts and comments tables only' . PHP_EOL;
    $help_message .= '      --migration=all --reset                 Reset all migrations' . PHP_EOL;
    $help_message .= '      --migration=all --reset --seed=all      Reset all migrations and insert all seeds' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '      --seed=all                              Insert all seeds' . PHP_EOL;
    $help_message .= '      --seed=user                             Insert user seed only' . PHP_EOL;
    $help_message .= '      --seed=user,comment                     Insert user and comment seeds only' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= "      --query='query' --fetch                 Execute SQL query and fetch results" . PHP_EOL;
    $help_message .= "      --query='query' --execute               Execute SQL query only" . PHP_EOL;
    $help_message .= "      --query='query' --execute --db=tinymvc  Execute SQL query from the database 'tinmvc'" . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '  --make (Manage resources build operations)' . PHP_EOL;
    $help_message .= '      --controller=posts                      Create posts controller' . PHP_EOL;
    $help_message .= '      --controller=posts --namespace=blog     Create posts controller in app\Controllers\Blog folder' . PHP_EOL;
    $help_message .= '      --resource=posts                        Create posts resources (controller, migration, model, views and routes)' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '      --model=posts                           Create posts model' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '      --migration=posts                       Create posts migration' . PHP_EOL;
    $help_message .= '      --migration=posts --m                   Create posts migration and model' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '      --seed=post                             Create post seed' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '      --request=AuthRequest                   Create AuthRequest in app\Requests folder' . PHP_EOL;
    $help_message .= PHP_EOL;
    $help_message .= '      --middleware=AuthPolicy                 Create AuthPolicy in app\Middlewares folder' . PHP_EOL;
    
    exit($help_message);
}
